version: '3.9'

services:
  app:
    build: ./app
    restart: always
    environment:
      - MONOGOURL=mongodb://mongodb_container:27017/mydb
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest  # Use the latest MongoDB Docker image
    container_name: mongodb_container
    volumes:
      - mongodb_data:/data/db  # Map a host directory to store MongoDB data
    restart: unless-stopped
volumes:
  mongodb_data: